name: Deploy

on:
  push:
    branches: [aws]

env:
  AWS_REGION: eu-north-1
  ENVIRONMENT: dev
  LAMBDA_CODE_BUCKET: ${{ secrets.LAMBDA_CODE_BUCKET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install production dependencies
        run: yarn install --production --frozen-lockfile

      - name: Zip code and dependencies
        run: |
          mkdir -p deploy_package
          shopt -s extglob
          cp -r !(deploy_package) deploy_package/ || true
          cd deploy_package
          zip -r ../code.zip . -x "*.git*" ".github/*" "test/*" "*.env*" "*.DS_Store" "node_modules/.bin/*"
          cd ..

      - name: Upload to S3
        run: aws s3 cp code.zip s3://${{ env.LAMBDA_CODE_BUCKET }}/${{ env.ENVIRONMENT }}/code.zip

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file template.yaml \
            --stack-name meetro-${{ env.ENVIRONMENT }} \
            --parameter-overrides \
              EnvironmentName=${{ env.ENVIRONMENT }} \
              LambdaCodeBucket=${{ env.LAMBDA_CODE_BUCKET }} \
              DomainName=${{ secrets.DOMAIN_NAME }} \
              GoogleClientId=${{ secrets.GOOGLE_CLIENT_ID }} \
              PAYSTACK_SECRET_KEY=${{ secrets.PAYSTACK_SECRET_KEY }} \
              GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              TWILIO_SID=${{ secrets.TWILIO_SID }} \
              TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }} \
              TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }} \
              RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
              RESEND_FROM_EMAIL=${{ secrets.RESEND_FROM_EMAIL }} \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --region ${{ env.AWS_REGION }} \
            --s3-bucket ${{ env.LAMBDA_CODE_BUCKET }}

      - name: Clean up
        if: always()
        run: |
          rm -rf deploy_package
          rm -f code.zip

      - name: Output Stack Status
        run: aws cloudformation describe-stacks --stack-name meetro-${{ env.ENVIRONMENT }} --query 'Stacks[0].StackStatus' --output text --region ${{ env.AWS_REGION }}